### ISSUE TITLE
Typo and feature request

### ISSUE THREAD

**Issue by kmahyyg** [skeeto/endlessh#11]
`    fprintf(f, "  -v        Print version information and exit\n");
`

Here, should be `-V` instead of `-v`.

By the way, could you please add a feature of trying save the connected clients' IP to a file?

**Comment by skeeto** [comment]
Thanks! Must have had a brain fart when I added that line to usage().

What do you mean for your feature request? The -v option already logs 
both the client IP and port when connecting and disconnecting. It's the 
"host=" and "port=" fields, though it's always in IPv6 form (since I 
don't really know the Right Way to display it as simple IPv4 when 
possible). As noted in the README:

    endlessh -v >endlessh.log 2>endlessh.err

**Comment by kmahyyg** [comment]
Just write the `host=` value to a `blacklist.log`, so that it could be used as a honey comb.
