### ISSUE TITLE
Support for systemd sockets

### ISSUE THREAD

**Issue by ashpooljh** [skeeto/endlessh#25]
A very typical scenario would be running this on port 22, which requires elevated privilege on most Linux systems. Even considering the almost non-existent attack surface, running as root just for that seems awkward. Systemd provides a convenient mechanism of adding the capability of using privileged ports (<1024) to unprivileged services, called [systemd sockets](https://www.freedesktop.org/software/systemd/man/systemd.socket.html). A basic TCP  socket would look like
```
[Unit]
Description=Endlessh socket

[Socket]
ListenStream=22
```
To take advantage of that, however, a program must be able to accept the input from that socket. There are two ways to do this, both mentioned in the linked article on sockets (either via systemd's native socket passing interface (see [sd_listen_fds](https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html#)(3) for details) or via the traditional [inetd(8)](https://www.freebsd.org/cgi/man.cgi?inetd(8))-style socket passing (i.e. sockets passed in via standard input and output, using StandardInput=socket in the service file))  I wonder if it is possible to add support for that to Endlessh.

**Comment by skeeto** [comment]
There's already a basic systemd configuration at util/endlessh.service. 
I haven't used it or tried it, so let me know if it's missing something 
important.

As for systemd sockets, I don't think they're useful in this case. The 
simple use case is having systemd start a process per connection with 
the socket connected standard input/output. However, this defeats the 
entire purpose behind Endlessh's implementation: minimal resource 
overhead. It should be able to trap at least tens of thousands of 
clients at once without any practical disruption to the rest of the 
system. So I don't want to pay for an entire process for each 
connection. Besides, if you were going to do that, you could replace 
Endlessh with just a few lines of C: a loop that alternates between 
sleep(3) and write(2) (as discussed in my article).

The other way is to let systemd pass file descriptors to the service via 
sd_listen_fds(). So I guess that allows systemd to control the listening 
socket, but this requires a complex, systemd-specific file descriptor 
dance for accepting those sockets (e.g. using dup2(2) to move sockets 
out of the way, etc.). That doesn't sound more secure. Besides, I prefer 
to trust the process that's _not_ connected to dbus when dealing with 
hostile connections.

**Comment by ashpooljh** [comment]
Sorry for the confusion with the `.service` file, I didn't realize it was there.

The points against using systemd sockets are absolutely fair, and after
giving it more thought, I agree that it would only make things more 
clumsy and vulnerable. For those interested in the approach I ended
up using, I added these lines to the `.service` file in the `[Service]` 
section:

```
User=nobody
Group=nogroup
PermissionsStartOnly=true
ExecStartPre=/sbin/setcap CAP_NET_BIND_SERVICE=+eip /opt/endlessh/endlessh
```

That way, the `endlessh` binary runs as `nobody:nogroup`, but is given
a special capability just to bind to a "privileged" socket. 
The `PermissionsStartOnly=true` line ensures that only the `ExecStart`
is run with the specified user and group, and not `ExecStartPre`, which
in this case needs to be run as a superuser.

**Comment by skeeto** [comment]
Thank you for the follow-up information.

**Comment by nbraud** [comment]
@skeeto I would suggest reopening this issue:
- the rationale for closing it (avoiding to start a process per connection) is inaccurate: per-connection processes is neither necessary nor the default when using systemd activation;
- `setcap CAP_NET_BIND_SERVICE=+eip` grants more privileges than necessary/desirable: the process can listen on any privileged port of any interface, and never drops `CAP_NET_BIND_SERVICE`;
- `setcap` hacks are really awkward for distributions; for instance, I would not ship `/usr/bin/endlessh` in Debian with a capability flag, as it would grant all users the ability to start a tarpit on any (privileged) port;
- using socket activation, it would be possible to further restrict the service with `PrivateNetwork`, denying it access to the network (aside from the socket it is given when executed).

**Comment by skeeto** [comment]
@nbraud, what would it take to permit socket activation? How would it 
work? I'm actually not familiar with running services under systemd and 
configuring capabilities. The unit file under util/ was not written by 
me, rather contributed by others, and I'm not committed to anything in 
particular in that configuration.

**Comment by nbraud** [comment]
@skeeto Essentially, socket activation works by having systemd (or whatever other service manager, really) open the socket, and when someone connects to it, the daemon is spawned and given the file descriptor.

There are two main options for getting the file descriptor from `systemd`:
- the systemd unit specifies `StandardInput=socket`, in which case the daemon's `stdin` (fd 0) is the socket;
- use [`sd_listen_fds(3)`] (or some equivalent) to get the file descriptor (which is AFAIK going to be fd 3, aka `SD_LISTEN_FDS_START`).

Given that `endlessh` only ever expects a single file descriptor, I don't think it makes sense to pull in `libsystemd` for `sd_listen_fds(3)` (even as an optional dependency); a command-line flag signalling that the socket is already open and available as file descriptor 0 would work fine.

[`sd_listen_fds(3)`]: https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html

**Comment by ashpooljh** [comment]
@nbraud `systemd` nowadays appears to have a standard way of bestowing capabilities upon services via the `AmbientCapability` directive. So no need to alter the executable capabilities via `setcap`.

**Comment by nbraud** [comment]
BTW, I forgot to mention, but using `stdin` for socket activation also works out-of-the-box with some other non-`systemd` service managers, like [`s6`].

[`s6`]: https://www.skarnet.org/software/s6/socket-activation.html

**Comment by skeeto** [comment]
I've read through some of the documentation and I'm stumped. I can't 
find any kind of socket activation that I haven't already dismissed as 
non-applicable to Endlessh. A couple of times I thought I found it, but 
it just turned out to be sloppy writing in the systemd documentation. 
For example, this page:

https://www.freedesktop.org/software/systemd/man/systemd.socket.html

Says "sockets passed in via standard input and output", where the key 
word here is "via". That makes it sound like stdin will be a unix domain 
socket and it will be used for file descriptor passing. Further reading 
indicates it's actually "as standard input and output" rather than 
"via". There's zero benefit to inetd-style socket activation with 
Endlessh because it would defeat the purpose. It would replace the only 
valuable part (low-resource socket juggling) with something far less 
efficient (process per socket).

And, as I said, I'm not interested in integrating with sd_listen_fds(). 
That would require rewriting most of the program. At that point it may 
as well just be a different project altogether: a systemd port of 
Endlessh.

I can't find any other kind of socket activation, especially one based 
on stdin. I *can* imagine an approach where a listen socket is passed as 
standard input (or, really, any other file descriptor). For example, 
systemd creates and binds the listen socket, fork(), dup() the socket 
over fd 0, setuid() or whatever, then exec() the service. As far as I 
can tell this feature doesn't exist.

**Comment by nbraud** [comment]
See #40 for an implementation proposal.

**Comment by russdill** [comment]
Socket activation would be really helpful as systemd.socket allows a lot of control over how the socket behaves. The most useful to me is "BindToDevice=" so I can specify that endlessh only accept connections on my internet facing interface and then I can run ssh on port 22 on my network interface without juggling things with nftables or hardcoding listen addresses that can change dynamically due to DHCP.
