### ISSUE TITLE
Impact on NAT router

### ISSUE THREAD

**Issue by ftiede** [skeeto/endlessh#28]
How is the impact of endlessh if running behind a NAT router with port forwarding?
Especially on the router in this case, as the NAT router would have to monitor up to 4096 connections while the server behind it handles the "keeping clients busy" part.

An alternative I have would be to install endlessh on the NAT router, but for this I'd need a more recent "release" than 0.1, as that is hardly compatible with the package manager in use. So I would be grateful if the current state of endlessh could be tagged as a "release" version.

**Comment by skeeto** [comment]
The impact on a NAT router could be significant since it too has to 
track some state for every connection. I don't really know how much 
consumer routers have improved, but, only a decade ago, it wasn't 
unusual for a single, busy BitTorrent client to completely knock down a 
mid-range home router — mostly due to the crappy, cheap memory they'd 
put in those things. Endlessh would have a similar sort of impact.

Moving Endlessh to the router would reduce the overall resource usage 
since it eliminates the duplication, but it would increase the load on 
the router, since it has to track even more information per connection 
(receive buffer, etc.).

I've tagged release 1.0 for you.

**Comment by ftiede** [comment]
Absolutely perfect, thanks a lot.
