### ISSUE TITLE
Would be nice if it dropped privs / chrooted if running as root

### ISSUE THREAD

**Issue by algernon** [skeeto/endlessh#3]
I'm about to run Endlessh on port 22, for which I need to run it as root to be able to bind to it. While it doesn't read anything from the clients, so exploiting it would be quite a challenge, I'm still uneasy running things as root, long-term, if I can avoid it.

Would it be possible to drop privileges once bound to the port, if running as root? Perhaps even chroot into an empty dir too?

I can prepare a pull request for both, if the idea is acceptable to you.

**Comment by ml-** [comment]
I agree that this would be a good addition for users running a minimal linux.
This specific use-case however can also be solved with capabilities.

For example using systemd, you can add the following to your service file:
```ini
User=nobody
Group=nobody
AmbientCapabilities=CAP_NET_BIND_SERVICE
```
You will have to set `PrivateUsers` to `false` in case you're using the included systemd service file. That's the tradeoff. There are a lot more isolation shenanigans you can do with systemd though.

**Comment by skeeto** [comment]
I had looked into dropping privileges, but it seemed messy and not worth 
it so I dropped the idea. As @ml- pointed out, today there are better 
ways for systems to impose the policy they want on services.

However, if it's pretty straightforward I'll accept a PR to do it. I 
imagine it being a new configuration option that indicates the final 
user and group (separate options for each?). This option should default 
to null/empty/disabled/etc. so it only happens when requested.

**Comment by algernon** [comment]
Truth be told, I _am_ using systemd, but completely forgot about it being able to do the privdrop for me. As such, I'll be using that instead of implementing it for Endlessh. Thanks for the instructions!

Closing this issue, 'cos there are better ways to accomplish the same thing.
