### ISSUE TITLE
Connection established, but no banner is received

### ISSUE THREAD

**Issue by thalst** [skeeto/endlessh#48]
Hi,

Thanks for the awesome program. I'm running 

endlessh -4 -d 10000 -p 22 -v -l 32

and as soon as I hit enter, port 22 starts accepting connections, but no banner is received on the client side. It just hangs. Is that a normal behavior?

Regards,

Thiago

**Comment by changchichung** [comment]
I have the same issue.

**Comment by skeeto** [comment]
That's exactly how it's supposed to work. The SSH client connects but 
never makes progress, hanging forever. The "banner" in this case isn't 
the text displayed to the user when logging in, but a part of the 
protocol identifying the server version, etc. It's unauthenticated, 
unencrypted information not displayed to users. If you connect with 
telnet then you *will* see this banner since telnet isn't speaking the 
SSH protocol.

**Comment by thalst** [comment]
Incredible. Many thanks!
